### ISSUE TITLE
Cannot locate new Gmock

### ISSUE THREAD

**Issue by vanyasem** [ubports/content-hub#1]
I get this error while building on Arch GNU/Linux (amd64):
```
CMake Error at cmake/FindGtest.cmake:18 (message):
  google-mock package not found
```
Gmock and Gtest are installed. Mir is able to detect their existence.

I assume that this commit in Mir https://github.com/MirServer/mir/commit/e7bbc0f2c7919acc770070ab2a9e27bd43eb8031 introduced support for it.

Same as https://github.com/ubports/ubuntu-download-manager/issues/2

**Comment by UniversalSuperBox** [comment]
I believe this was fixed by https://github.com/ubports/content-hub/pull/7 or https://github.com/ubports/content-hub/pull/9
