### ISSUE TITLE
ContentStore stores only certain ContType types

### ISSUE THREAD

**Issue by cibersheep** [ubports/content-hub#19]
According to the [docs](http://api-docs.ubports.com/sdk/apps/qml/Ubuntu.Content/ContentStore.html) doing `peer.request(appStore)` will store the file imported in `.local/.../appname.username` (for ContentScope.App) and `~/` for ContentScope.User

```
// Optional store to use for persistent storage of content
ContentStore {
    id: appStore
    scope: ContentScope.App //or ContentScope.User
}
```

This works if ContentType for the ContentPeerPicker is:
Pictures
Documents
Music

This does not work (with no error) for:
All
Unknown
Contacts
Videos
Links
EBooks
Text

I didn't test it for ContentScope.System as I don't know where the files should go

**Comment by cibersheep** [comment]
I see, this might be why: https://github.com/ubports/content-hub/blob/xenial/src/com/ubuntu/content/hub.cpp#L183

I could try to link 
Videos to Videos directory
EBooks, Text to Documents directory
Contacts, Links, Unknown to Documents directory? to new directories (Contacts, Links, Unkown)?
And All?

Would be this correct?

**Comment by UniversalSuperBox** [comment]
This issue has been moved to https://gitlab.com/ubports/core/content-hub/-/issues/1. Please continue any further discussion there.
