### ISSUE TITLE
Unknown option 'qt'

### ISSUE THREAD

**Issue by vanyasem** [ubports/content-hub#4]
I get this error when building on Arch GNU/Linux (amd64)
```
Unknown option 'qt'.
make[2]: *** [docs/qml/CMakeFiles/qmldoc.dir/build.make:58: docs/qml/CMakeFiles/qmldoc] Error 1
make[1]: *** [CMakeFiles/Makefile2:4153: docs/qml/CMakeFiles/qmldoc.dir/all] Error 2
```

```
Invalid argument: -qt=qt5
make[2]: *** [import/Ubuntu/Content/CMakeFiles/Content_generated_files.dir/build.make:58: import/Ubuntu/Content/plugins.qmltypes] Error 1
```

The troubling options resides in `doc/qml/CMakeLists.txt` on line 6, and in (`import/Ubuntu/Content/CMakeLists.txt`).

The issue is related to `qdoc`: `/usr/bin/qdoc -qt=qt5`

Same as https://github.com/ubports/ubuntu-download-manager/issues/6

**Comment by UniversalSuperBox** [comment]
I am unsure if this issue affects content-hub any more. If it does, please file a new issue at https://gitlab.com/ubports/core/content-hub
