### ISSUE TITLE
Fails to build if XDG_RUNTIME_DIR is not set

### ISSUE THREAD

**Issue by vanyasem** [ubports/content-hub#5]
The build fails on `make` step if XDG_RUNTIME_DIR is not set in the enviroment:
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-builduser'
QQmlComponent: Component is not ready
```

Creating `mkdir -p /tmp/runtime-builduser` and setting `XDG_RUNTIME_DIR=/tmp/runtime-builduser` before `make` solves the issue.

**Comment by vanyasem** [comment]
Same as https://github.com/ubports/ubuntu-ui-toolkit/issues/14

**Comment by UniversalSuperBox** [comment]
content-hub has moved to https://gitlab.com/ubports/core/content-hub. If this issue is still relevant, please file a new one there.
